name: GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'   # Only run if something inside docs/ changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs   # Path that should be served

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
