name:  build kernel with Nix
on: workflow_dispatch
 inputs:
  kernel_attribute:
   type: string
   equired: true
jobs:
    build_and_cache:
    run-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
