name: build kernel with Nix
on:
  workflow_dispatch:
    inputs:
      kernel_attribute:
        type: string
        required: true
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v15
      with:
        name: tkt-cache
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}" #
    -  run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
    - run: nix build --no-write-lock-file --print-out-paths  --print-build-logs ${{ github.workspace }}#${{inputs.kernel_attribute}}

